---
application:
  name: "doinghisjob"
  project: "doinghisjob"
  organization: "QoveryCommunity"
  
routers:
- name: "main-doinghisjob"
  routes:
  - application_name: "doinghisjob"
    paths:
    - "/"
